### ISSUE TITLE
breaking WP 5.5 sitemap

### ISSUE THREAD

**Issue by atomGit** [keycdn/cache-enabler#101]
Cache Enabler v1.4.4 seems to be breaking the default WP v5.5 sitemap (/wp-sitemap.xml) - it looks like /wp-sitemap-index.xsl is not loading

when CE is enabled, it takes 1 or 2 refreshes of wp-sitemap and i'm seeing this where all formatting is gone...

`https://12bytes.org/wp-sitemap-posts-post-1.xmlhttps://12bytes.org/wp-sitemap-posts-page-1.xmlhttps://12bytes.org/wp-sitemap-taxonomies-category-1.xmlhttps://12bytes.org/wp-sitemap-users-1.xml`

this is reproducible about 90% of the time, but not 100%

**Comment by atomGit** [comment]
just want to verify that this issue was not resolved in the 1.4.5 release, correct? i looked at the commit and i can't tell

also, if this helps, i found that after enabling CE, the sitemap always loads correctly the first time - only after a refresh/reload does it go wonky

**Comment by coreykn** [comment]
Just so you're aware, if an issue is resolved the status will be updated accordingly. This issue has not been resolved yet. The temporary solution is adding `/\.xsl|\.xml/` as an excluded page path (you'll need to clear your cache afterwards). I'll have a solution for this within the next day or two.
