### ISSUE TITLE
Add filter/constant to set "cdn_enabler.url" (improvement suggestion)

### ISSUE THREAD

**Issue by mibu31** [keycdn/cache-enabler#107]
Hi there,
Is there any chance we can get a filter or constant added to override the "CDN URL" var? 
This should be settable programmatically / configurable in code imo.
Cheers.

**Comment by coreykn** [comment]
This is the repository for the Cache Enabler plugin (not the [CDN Enabler](https://github.com/keycdn/cdn-enabler) plugin).

**Comment by mibu31** [comment]
@coreykn So sorry, my mistake, I'll repost!
