### ISSUE TITLE
file permissions notice broken

### ISSUE THREAD

**Issue by nosilver4u** [keycdn/cache-enabler#114]
The notice displayed when file permissions are incorrect on the caching directory ends with "Please change the ."
It seems the sprintf() is missing the second placeholder for the text 'file permissions': https://github.com/keycdn/cache-enabler/blob/master/inc/cache_enabler.class.php#L1963

**Comment by coreykn** [comment]
Thanks for bringing this to our attention, @nosilver4u. We sincerely appreciate it. This has been fixed and will be available in version 1.4.8.
