### ISSUE TITLE
Favicon.ico - 404

### ISSUE THREAD

**Issue by tobias992** [keycdn/cache-enabler#118]
Hi Community,

with new version there is a Bug with Favicons.

When i visit my domain.com/favicon.ico i get an 404 error.

I had to add these small snippet to my nginx Config:
location = /favicon.ico { try_files $uri $uri/ /index.php?$query_string; }

After add this snippet i had a correct redirect to my favicon.

**Comment by coreykn** [comment]
I'm unable to replicate this issue with version 1.4.8. As far as I'm aware the Cache Enabler plugin would not even be related to this issue. You can confirm this by deactivating the Cache Enabler plugin.
