### ISSUE TITLE
incompatible with image CDN plugins

### ISSUE THREAD

**Issue by philbraun** [keycdn/cache-enabler#120]
When using CDN-based image plugins like Flying Images or ShortPixel Adaptive Images, Cache Enabler changes URLs from the CDN-based ones to the basic WordPress-based ones when writing the cache file.

**Comment by coreykn** [comment]
The Cache Enabler plugin would not be change the URLs in this case, however, it's possible the issue is related to the output buffer. Can you please provide the before and after outputs? For example, a condensed HTML output of before the page is cached and after the page has been cached.

**Comment by philbraun** [comment]
Does this help?
[cache-enabler-before-after.zip](https://github.com/keycdn/cache-enabler/files/5180279/cache-enabler-before-after.zip)

**Comment by coreykn** [comment]
Yes, that's very helpful. Thank you for providing that information @philbraun. This issue does appear to be related to the output buffer timing (similarly related to issue #78). The Cache Enabler output buffer timing will be updated to start earlier, which I believe will resolve this issue. Further updates to follow.
