### ISSUE TITLE
Feature proposal: Brotli support

### ISSUE THREAD

**Issue by nlemoine** [keycdn/cache-enabler#143]
Hi @coreykn!

I've been recently implementing brotli compression for the assets part (css, js, svg, etc.) of the projects I'm working on and I thought It would be great to have Brotli for static cached page too. The performance gain is worth it.

You'll find everything here: https://github.com/nlemoine/cache-enabler/tree/feature-brotli

I think compression settings could be removed. The serving [cache](https://github.com/nlemoine/cache-enabler/blob/feature-brotli/advanced-cache.php#L135) [methods](https://github.com/nlemoine/cache-enabler/blob/feature-brotli/inc/cache_enabler_disk.class.php#L202) already does the `http_accept_encoding` checks so no Brotlied or Gzipped page will be served to browsers that don't support them.

Let me know what you think.

**Comment by coreykn** [comment]
#1

**Comment by nlemoine** [comment]
Whoops, sorry, I saw that issue earlier, just forgot about it.

Are you still interested in a PR?

**Comment by coreykn** [comment]
No problem. We are definitely interested. Let's continue this discussion in the issue mentioned above instead.
