### ISSUE TITLE
Just found that after the 1.5.0 update, visitors do not load the cache file

### ISSUE THREAD

**Issue by gfwyuexia** [keycdn/cache-enabler#151]
Just found that after the 1.5.0 update, visitors do not load the cache file
Then found that the source code is updated
Replace cache_ enabler_ disk.class.php file
it's work！

**Comment by coreykn** [comment]
Fixed in 4a8aa99 and released in version 1.5.1. Can you please confirm?

**Comment by gfwyuexia** [comment]
yes，it's works
