### ISSUE TITLE
cache not cleared on WooCommerce stock update after successful order

### ISSUE THREAD

**Issue by ChessDragon136** [keycdn/cache-enabler#165]
Hi,

Recently started to use stock management on my WooCommerce site but have noticed that stock numbers are not accurately reflected as the page has not been re-cached on any given user purchase. 

Only option selected in plugin setting is:  Pre-compress cached pages with Gzip.

Any help appreciated.

Cache Enabler: Version 1.5.5
Wordpress: 5.4.4
WooCommerce: 3.9.2

**Comment by coreykn** [comment]
Thanks for bringing this up, @ChessDragon136. You're right, the product page cache is not automatically being cleared after the stock has been updated after a successful order. I'm lost at how I thought the new cache clearing for post actions covered this. I must have only been testing this when the stock quantity was manually updated and assumed the same hook was always fired. 😞 I apologize for that. The solution for this will be released shortly.

**Comment by ChessDragon136** [comment]
Thanks for looking into this - Thought it was just me.

Can you please implement the hooks into both complete and on-hold, so orders paid by BACS, Cash or some other manual method are also stock reduced at the time of ordering. 

woocommerce_payment_complete
woocommerce_order_status_on-hold

**Comment by coreykn** [comment]
You're most welcome. I believe I can just use the stock related hooks for this as those are fired whenever the stock is updated, but I won't be certain until I create the solution. I'll make sure the page and associated cache are cleared by default (or the complete cache if the setting is enabled) whenever the stock is automatically updated just like it is when the stock quantity is manually updated. I'll have this ready to be released not next week but the beginning of the week after that (week 49) as I'll be offline next week. I'm sorry for that delay but you can create your own solution in the meantime if you'd like.
