### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by szepeviktor** [keycdn/cache-enabler#171]
Would you welcome a PR introducing namespaces?

`namespace KeyCDN\WordPress\Cache_Enabler;`

[![kép](https://user-images.githubusercontent.com/952007/99716938-fe0bf180-2aa8-11eb-8f88-98bd5af33ec2.png)](https://www.php.net/manual/en/language.namespaces.rationale.php)

**Comment by coreykn** [comment]
Thanks for brining this discussion up, @szepeviktor. A few months ago I had considered the same thing but given how the class names were already defined I didn't move forward with this. Can you please provide a little more clarity on how you'd introduce this change?

**Comment by szepeviktor** [comment]
@coreykn Simply

```php
final class Cache_Enabler_Disk {

👇 

namespace KeyCDN\WordPress\Cache_Enabler;

final class Disk {
```

**Comment by szepeviktor** [comment]
... of course modify the autoloader and `add_action( 'plugins_loaded', array( __NAMESPACE__ . '\\Plugin', 'init' ) );`

**Comment by coreykn** [comment]
Thank you for the confirmation. 🙂 Unfortunately I don't think this would be a good idea due to how the current classes are used out in the wild between Cache Enabler users and third party plugins.

**Comment by szepeviktor** [comment]
I suspected BC will be a blocker.

**Comment by szepeviktor** [comment]
It is extreeemly hard to ship software to user armed with a mouse.

**Comment by szepeviktor** [comment]
..although we may use `class_alias()` ...
