### ISSUE TITLE
Cache is always empty

### ISSUE THREAD

**Issue by skorzo** [keycdn/cache-enabler#18]
Hi !

I have been using Cache Enabler + Autoptimize for a few days without any issue.

Yesterday I changed the Expiry setting from 24 to 0, and after that change my cache was cleared but it has not been rebuilt again.

No matters what I try (disabling, deleting and reinstalling the plugin), the cache size is always "empty" and even the cache-enabler folder under "wp-content/cache" does not exist anymore.

Any suggestion about how to force a new cache?

Thanks !!

**Comment by svenba** [comment]
This is not a support forum.
