### ISSUE TITLE
Clear assets from CDN from within WP's backend

### ISSUE THREAD

**Issue by cristianraiber** [keycdn/cache-enabler#2]
Probably what would be one of the most useful features of this plugin.

**Comment by dramaturg** [comment]
The cache enabler isn't really the place to put this. We've implemented this in our [cdn-enabler](https://wordpress.org/plugins/cdn-enabler/) plugin.

**Comment by cristianraiber** [comment]
@dramaturg - ooops, yeah. Looks like I posted in the wrong repo.
