### ISSUE TITLE
cache HTTP and HTTPS pages separately

### ISSUE THREAD

**Issue by TylerBarnes** [keycdn/cache-enabler#20]
Hi there, I believe I've found a bug. I've been installing this on old sites that are http but occasionally cache enabler caches the pages with all the assets as https. This results in none of the page assets loading and I get an html only site. I could fix this with my htaccess but it seems like something the plugin should handle.

**Comment by svenba** [comment]
This is not a support forum and there isn't enough evidence for a bug.

**Comment by TylerBarnes** [comment]
I'm ditching all keycdn products. The support here is awful.

**Comment by coreykn** [comment]
WordPress topic: https://wordpress.org/support/topic/https-injected-into-http-site-2/
