### ISSUE TITLE
Cache 404 / error pages

### ISSUE THREAD

**Issue by janvitos** [keycdn/cache-enabler#213]
Hi,

In most WordPress cache plugins, there is an option to cache 404 / error pages. I believe this would be a great addition to Cache Enabler as caching repeat error pages can ease the load on the web server.

In the meantime, would there be any way of achieving this with an existing filter or similar?

Thanks!

**Comment by coreykn** [comment]
Thanks for your feature request, @janvitos. Like with our other requests let's see if anyone else is interested in this type of behavior before introducing it. If it were to be introduced it'd likely be through a filter hook, like maybe allowing cacheable HTTP status codes to be filtered where `200` is the default.

Unfortunately there isn't a way of achieving this right now, but the following snippet is what currently controls this behavior:

https://github.com/keycdn/cache-enabler/blob/19aa9382cdb06986a17826891975532a6119b14e/inc/cache_enabler_engine.class.php#L387-L390

**Comment by janvitos** [comment]
Thanks @coreykn.

I found that filter and did comment it out for the moment, enabling caching of all status codes, including 404.

The main reason why I think it would be beneficial is to prevent bots / attackers from requesting tons of 404 pages and possibly overloading the web server. Such requests have been hitting my web server lately, but fortunately, they have not yet been cause of concern. I would prefer to block those bots, but they are spoofing good bot user agents, so it's pretty hard. At least, by caching the 404 pages, this would reduce the load on my web server and prevent any possible future problems.

I know this might be a specific issue that not everyone has to deal with, but I still think it would make a great addition to the plugin.

Cheers.

**Comment by janvitos** [comment]
I've created a pull request with the necessary code modifications to enable caching of various response codes.

**Comment by janvitos** [comment]
I realized that although the logic works, the web server returns a 200 response code once the 404 page is cache. In reality, it would still need to return a 404.

**Comment by janvitos** [comment]
I was able to create a page rule to cache 404 pages with CloudFlare, so caching with the plugin is not necessary anymore.

Thanks.

**Comment by dekaSW** [comment]
Seems like the filtered value for `$bypass_cache` via hook is always evaluated after checking for this value in `deliver_cache()`  which is too late and thus cannot be overriden for this purpose. I guess it's due to the static class definitions or I'm missing something fundamental here.

**Comment by pacotole** [comment]
> The main reason why I think it would be beneficial is to prevent bots / attackers from requesting tons of 404 pages and possibly overloading the web server.

I also think that's a good point.

Ideally, we should cache the 404 page only once and then serve it for every not found URL.

As @janvitos mentioned, this would significantly reduce server load in case of an attack (or some bad shared links).

**Comment by pacotole** [comment]
I've created [a branch](https://github.com/keycdn/cache-enabler/compare/master...creame:cache-enabler:feature/404cache) that allows to store and serve 404 error pages (save for every page not only once).

If a page returns a 404 error, it is stored in the following format:
`path/to/page/404-{$scheme}index{$device}{$webp}.html{$compression}`

When deliver content from the cache, it checks if the default file (200) exists; if not, it checks for the 404 file. In the latter case, it adds the appropriate headers to indicate that it's a 404 error page.

Caching 404 errors is always enabled, but I think there should be an option to enable or disable this feature.

If you think this is a good idea, I'd be happy to submit a pull request.
