### ISSUE TITLE
1.7 Bug

### ISSUE THREAD

**Issue by tobias992** [keycdn/cache-enabler#218]
With Setting "precomress sites with gzip" only the .gz version is created. There is no normal .html file in cache folder

I think this cannot be a feature...

**Comment by janvitos** [comment]
I have also noticed the same thing.

**Comment by coreykn** [comment]
This updated handling was introduced in PR #211 and is expected. We do recommend checking out recent commits/PRs before opening a new issue as those contain a lot of information regarding the changes to the code base.

**Comment by nlemoine** [comment]
@coreykn Maybe you should write somewhere in the docs/readme something about your version policy.

I often have been quite surprised myself by some changes made across minor versions (from 1.x to 1.y) that would have usually been considered as breaking changes (like this last one in 1.7) in the SemVer world.
