### ISSUE TITLE
Version 1.8.2 on IIS

### ISSUE THREAD

**Issue by mmojadad** [keycdn/cache-enabler#288]
Hello
After update to version 1.8.1 and then 1.8.2, In \wp-content\cache\ folder "cache-enabler" and cache content not generate. I am using IIS, I faced the issue in both new versions.

Regards,

**Comment by coreykn** [comment]
While [debugging is enabled](https://wordpress.org/support/article/debugging-in-wordpress/#example-wp-config-php-for-debugging), like to a log file, does this still occur after deactivating and then activating the plugin? If yes, did you happen to receive any errors in that file?

Also, would it be possible for you to share your Site Health Info through our [contact form](https://www.keycdn.com/contact)? This can be obtained by going to the WordPress dashboard > Tools > Site Health > Info > **Copy site info to clipboard**.

**Comment by mmojadad** [comment]
@coreykn
I will try and inform you, Also already i am online and ready to provide you full remote access to the serve via anydesk if its helpful. Just message me via teletgram @modirafzar

**Comment by mmojadad** [comment]
Some more info : I tested it on 2 website on my server , Also a friend's website in another server  Win 2019 ( IIS ) with same result.

**Comment by coreykn** [comment]
Thank you, @mmojadad. That is really appreciated. I'm thinking this may be related to the use of the `$_SERVER['SCRIPT_FILENAME']` superglobal as I'm just noticing it's not in the CGI specs, which means it can't always be relied on. I do have a new solution that I'm working on.

Are you interested in testing this theory to see if it's applicable to your issue? It would take going to the `wp-content/plugins/cache-enabler/inc/cache_enabler_engine.class.php` file and temporarily replacing the first snippet in the latest version with the second snippet from version 1.7.2:

https://github.com/keycdn/cache-enabler/blob/612ada2b9eeb95f3017eddef654f80cfd39def0a/inc/cache_enabler_engine.class.php#L190-L197

https://github.com/keycdn/cache-enabler/blob/45db4c70580c3d03f13ec7bc1e627ad2ebc53135/inc/cache_enabler_engine.class.php#L211-L218

**Comment by mmojadad** [comment]
@coreykn 
I did the same modifications on cache_enabler_engine.class.php another domain ( Same Server ), But cache not generate. Any idea? more test ?

**Comment by mmojadad** [comment]
@coreykn 
Good news! Yes sure, I issue occur for the other site, I will provide you Site Health.
When version 1.8.3 will release?
