### ISSUE TITLE
1.8.4 fatal error after update

### ISSUE THREAD

**Issue by denathor** [keycdn/cache-enabler#294]
After updating to 1.8.4 my site throws random 500 errors.
And in the logs are lots of the following type errors.

server 500 errors after updating to 1.8.4
[Sun Sep 12 15:23:17.644722 2021] [php7:error] [pid 1410] [client 52.90.83.110:53928] PHP Fatal error: Uncaught Error: Call to undefined function wp_opcache_invalidate() in /nas/content/live/stagingdx/wp-content/plugins/cache-enabler/inc/cache_enabler_disk.class.php:1044\nStack trace:\n#0 /nas/content/live/stagingdx/wp-content/plugins/cache-enabler/inc/cache_enabler_engine.class.php(88): Cache_Enabler_Disk::get_settings(true)\n#1 /nas/content/live/stagingdx/wp-content/plugins/cache-enabler/inc/cache_enabler_engine.class.php(26): Cache_Enabler_Engine->__construct()\n#2 /nas/content/live/stagingdx/wp-includes/class-wp-hook.php(303): Cache_Enabler_Engine::start('')\n#3 /nas/content/live/stagingdx/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)\n#4 /nas/content/live/stagingdx/wp-includes/plugin.php(470): WP_Hook->do_action(Array)\n#5 /nas/content/live/stagingdx/wp-settings.php(578): do_action('init')\n#6 /nas/content/live/stagingdx/wp-config.php(125): require_once('/nas/content/li...')\n#7 /nas/content/live/stagingdx/wp-load.php(50): require_once('/nas/content/li...')\n#8 /nas/content/live/stagingdx/ in /nas/content/live/stagingdx/wp-content/plugins/cache-enabler/inc/cache_enabler_disk.class.php on line 1044

**Comment by coreykn** [comment]
What WordPress version are you running? Since version 1.8 Cache Enabler now requires WordPress 5.5 or higher.

**Comment by coreykn** [comment]
Ignore that, I see what the issue is here and will fix it shortly. A temporary workaround would be deactivating and then reactivating the plugin.

**Comment by denathor** [comment]
I couldn't even get to the admin page. i had to have the hosting company disable the plugin from their end to get the site back up.
