### ISSUE TITLE
Fatal error: Uncaught RuntimeException

### ISSUE THREAD

**Issue by angelo-at-webleaders** [keycdn/cache-enabler#319]
I just downloaded it and when I try to press "activate" I get this error:

Fatal error: Uncaught RuntimeException: SSH2 hostname is required in /var/www/xxx.nl/wp-content/plugins/cache-enabler/inc/cache_enabler_disk.class.php:1247 Stack trace: #0 /var/www/xxx.nl/wp-content/plugins/cache-enabler/inc/cache_enabler_disk.class.php(1296): Cache_Enabler_Disk::get_filesystem() #1 /var/www/xxx.nl/wp-content/plugins/cache-enabler/inc/cache_enabler_disk.class.php(426): Cache_Enabler_Disk::mkdir_p() #2 /var/www/xxx.nl/wp-content/plugins/cache-enabler/inc/cache_enabler.class.php(412): Cache_Enabler_Disk::create_settings_file() #3 /var/www/xxx.nl/wp-content/plugins/cache-enabler/inc/cache_enabler.class.php(366): Cache_Enabler::on_update_backend() #4 /var/www/xxx.nl/wp-content/plugins/cache-enabler/inc/cache_enabler.class.php(609): Cache_Enabler::update_backend() #5 /var/www/xxx.nl/wp-content/plugins/cache-enabler/inc/cache_enabler.class.php(137): Cache_Enabler::each_site() #6 /var/www/xxx.nl/wp-inc in /var/www/xxx.nl/wp-content/plugins/cache-enabler/inc/cache_enabler_disk.class.php on line 1260

Can anyone please tell me what might be the issue?

**Comment by angelo-at-webleaders** [comment]
Is there still support for this plugin or is it dead?

**Comment by futtta** [comment]
I'm not part the KeyCDN/ Cache Enabler team (and they do follow up on questions here, but it's weekend after all), but I did a quick search and [found this forum topic that is related](https://wordpress.org/support/topic/permissions-issue-28/), maybe that helps? :-)

**Comment by angelo-at-webleaders** [comment]
That indeed solved the problem, but now other plugins won't work so yeah... kinda weird that this plugin is depending on that global. But for now thanks for your help!!!

**Comment by angelo-at-webleaders** [comment]
That indeed solved the problem, but now other plugins won't work so yeah... kinda weird that this plugin is depending on that global. But for now thanks for your help!!!
