### ISSUE TITLE
Save html cache files directly to S3

### ISSUE THREAD

**Issue by hj-collab** [keycdn/cache-enabler#328]
Hi,

Many people run websites in a cluster. It will be great for them if KeyCDN cache enabler saves the generated cache files directly to S3 bypassing the file system. There are some plugins for media library but none for cache. CDN will cache the S3 files after first request ensuring fast loading the after first request.

Best regards,

**Comment by vaska94** [comment]
It's generally not a good idea to use S3 as a Cache. 
https://docs.aws.amazon.com/whitepapers/latest/s3-optimizing-performance-best-practices/using-caching-for-frequently-accessed-content.html
Maybe another plugin that uses Redis as a cache Backend is better fit for you.
P.s: I'm not a developer of Cache Enabler, Just user
