### ISSUE TITLE
Admin toolbar navigation entries messing up layout

### ISSUE THREAD

**Issue by rexblack** [keycdn/cache-enabler#41]
First of all, thanks for providing CacheEnabler-Plugin. It works great and appears to be the best solution I tried so far.

When having CacheEnabler, Autoptimizer plus (probably) one other Plugin (e.g. Yoast SEO which itself only shows an icon here) being displayed on the adminbar, it messes up layout for smaller desktop screens.

<img width="1110" alt="bildschirmfoto 2018-10-24 um 11 33 07" src="https://user-images.githubusercontent.com/424581/47423254-e4423800-d784-11e8-9358-09cd22b17007.png">

Actually one could hardly call this a bug and also, it's not related to CacheEnabler in particular. Moreover it is because of the plugin nature of Wordpress and its dynamic toolbar. Might also not be seen as critical because only a certain range of dimensions is affected in some cases.
It's a common issue with header navigation having lots of entries, in particular regarding localization.

But since it could be easily fixed or let's say "disarmed" on your side, it would be great if this could be improved.

Possible Solutions would of course be, e.g. Using an icon with the label as title-tooltip or having both menu items collapsed in a dropdown.

**Comment by svenba** [comment]
@TomaszGasior agreed.
