### ISSUE TITLE
wp-cli commands

### ISSUE THREAD

**Issue by jjtroberts** [keycdn/cache-enabler#45]
Would be great to have the plugin tie into the `wp cache flush` command and purge the cache/cache-enabler/* directory, or have its own wp-cli command to clear those pages. We run `wp transient delete-all && wp cache flush` after each Jenkins deployment. While that takes care of the Redis object cache, it does not affect the advanced-cache which must be purged from the UI or a scripted `rm -rf <path-to-cache-dir>` command.

I can do this, however, `wp eval "Cache_Enabler::clear_total_cache();"`

**Comment by svenba** [comment]
This is going to be available in v1.3.5.
