### ISSUE TITLE
Please make new release for critical fixed bugs

### ISSUE THREAD

**Issue by mcnilz** [keycdn/cache-enabler#46]
https://github.com/keycdn/cache-enabler/commit/d81cd4718f57df2ee428d4703a859eae3fec287b fixed a critical bug but you did not release a new version. You just silently updated the 1.3.1 version that I installed before the fix. So I never got the critical update.

**Comment by svenba** [comment]
Fixed in https://github.com/keycdn/cache-enabler/commit/0751497066199cdfca846ed5e4dc3e8d3dc7fa2b
