### ISSUE TITLE
Allow custom cache location

### ISSUE THREAD

**Issue by nlemoine** [keycdn/cache-enabler#5]
Cache is currently saved to `WP_CONTENT_DIR. '/cache/cache-enabler'`. 

This makes cached pages accessible if you hit the file URL (ex: http://domain.com/wp-content/cache/cache-enabler/domain.com/hello-world).

It would be nice to allow developers to filter this location.

**Comment by dramaturg** [comment]
This is unlikely to be of use to many people as we have to stay within WP_CONTENT_DIR for most installations. It's easy enough to secure the cache directory through your web server configuration, isn't it?
