### ISSUE TITLE
Configuration of the plugin by wp-cli

### ISSUE THREAD

**Issue by TomaszAdamiec** [keycdn/cache-enabler#53]
Hi,

great plugin. It would be even better if the plugin could be configured by wp-cli :)

Especially:
Clear the complete cache if a new post has been published
Clear the complete cache if a new comment has been posted
Clear the complete cache if any plugin has been upgraded

**Comment by svenba** [comment]
The version v1.3.5 will include WP CLI commands to purge the cache.
