### ISSUE TITLE
Add filter to $converted_data

### ISSUE THREAD

**Issue by davidpom** [keycdn/cache-enabler#57]
On file  cache_enabler_disk.class.php, line 290, would be great to have a filter inside $converted_data variable, e.g.:

`$converted_data = apply_filters( 'cache_enabler_disk_converted_content', preg_replace_callback($regex_rule,'self::_convert_webp',$data) )`

This way anyone can filter the content to make any replacements and have them store in cache (e.g. add webp to bg images).

**Comment by svenba** [comment]
Pull request is welcome :)

**Comment by germanoronoz** [comment]
Good news!
