### ISSUE TITLE
Only clear specific products cache on woocommerce stock change

### ISSUE THREAD

**Issue by gamag** [keycdn/cache-enabler#61]
Currently, after a stock change in woocommerce, the full cache is cleared. For a busy online shop, this basically disables caching,  since the cache is already cleared again before it could be (fully) rebuild.

The obvious solution is to only clear the product that actually changed. [RedCastor/cache-enabler](https://github.com/RedCastor/cache-enabler/blob/master/inc/cache_enabler_woocommerce.class.php) has working code that does this.

see also:
https://wordpress.org/support/topic/cache-gets-cleared-every-time-a-stock-change-happens-at-woocommerce/

**Comment by svenba** [comment]
https://github.com/keycdn/cache-enabler/issues/82
