### ISSUE TITLE
[Security] Don't store json config in public accessible place

### ISSUE THREAD

**Issue by mahnunchik** [keycdn/cache-enabler#69]
Don't store json config in public accessible place, I mean `wp-content/cache/cache-enabler-advcache`.

Cache config leaks to everybody.

**Comment by mahnunchik** [comment]
https://github.com/keycdn/cache-enabler/blob/master/advanced-cache.php#L24-L32

**Comment by mahnunchik** [comment]
At least `incl_attributes` and `excl_cookies`  must not be shown to client.

**Comment by svenba** [comment]
You can restrict this with you web config if you are concerned about it.

**Comment by mahnunchik** [comment]
Why not hide this config by design? Ar keep it as `.php` file hidden by default?
