### ISSUE TITLE
Why code duplication?

### ISSUE THREAD

**Issue by mahnunchik** [keycdn/cache-enabler#70]
Hi,

There are almost the same code:

* https://github.com/keycdn/cache-enabler/blob/master/advanced-cache.php
* https://github.com/keycdn/cache-enabler/blob/master/inc/cache_enabler_disk.class.php#L185

Why?

**Comment by svenba** [comment]
This is by purpose.

**Comment by mahnunchik** [comment]
Which purpose? Could you be a bit more informative?
