### ISSUE TITLE
Cache in minutes or throughput

### ISSUE THREAD

**Issue by arianitu** [keycdn/cache-enabler#77]
Hey, I love the plugin, great job. The only issue I've found is that you can only set a cache time every hour instead of being able to set a cache time in minutes.

I think minutes are a better system or accepting fractional hours.  We're looking for a caching system to help with load spikes, not necessarily to cache for long periods of time.

It would actually be awesome to have a cache system based on throughput. So start caching as throughput starts to get to > 1 s for example, else do not cache. 

Maybe starting with accepting minutes is best tho? Or fractional hours?

**Comment by svenba** [comment]
While your use case is interesting, hours are better suited for the majority of the plugin users.
