### ISSUE TITLE
Default cache inclusions do not work unless set

### ISSUE THREAD

**Issue by lukecav** [keycdn/cache-enabler#79]
`/^utm_(source|medium|campaign|term|content)$/`

Default if unset: /^utm_(source|medium|campaign|term|content)$/

**Comment by typingsloth** [comment]
I've been unable to replicate this issue when using Cache Enabler 1.3.5 and WordPress 5.4.2. The default value is unset and all query string combinations tested don't bypass the cache. Do you have an example that I can use to replicate this issue?

**Comment by lukecav** [comment]
Not able to replicate the issue now, since the issue happened on-site back in April.
