### ISSUE TITLE
HTTP/2 question

### ISSUE THREAD

**Issue by TylerBarnes** [keycdn/cache-enabler#8]
Hey there,
great plugin! I love cache enabler.
The description lists that this is "HTTP/2 focused". 
What does that mean? 
Are the page assets like css & js being pushed?

**Comment by svenba** [comment]
This is not a support forum.

**Comment by TylerBarnes** [comment]
I meant what does it mean in the context of this plugin? As in the plugin states that it's HTTP/2 focused but not how it achieves that. I enabled this on a server that supports HTTP/2 and didn't see anything coming across as HTTP/2. I was also looking to see if I could configure it to push certain assets. 

I'm not looking for a description of HTTP/2, the documentation is just inadequate.
